# Generated by Django 6.0.4 on 2026-04-10 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_category_item_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchlocation",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="warehouse.itembatch",
                verbose_name="批次",
            ),
        ),
        migrations.AlterField(
            model_name="batchlocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_locations",
                to="warehouse.location",
                verbose_name="货位",
            ),
        ),
        migrations.AlterField(
            model_name="batchlocation",
            name="quantity_units",
            field=models.PositiveIntegerField(default=0, verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="item",
            name="active",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="item",
            name="has_shelf_life",
            field=models.BooleanField(default=False, verbose_name="是否有保质期"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="item",
            name="packaging_volume",
            field=models.DecimalField(
                decimal_places=3,
                default=1.0,
                help_text="用于计算货位容量占用",
                max_digits=10,
                verbose_name="单件体积",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size_text",
            field=models.CharField(
                blank=True,
                help_text="包装规格或尺寸描述",
                max_length=120,
                verbose_name="尺寸/包装",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sku_code",
            field=models.CharField(
                help_text="数字识别码（扫码或输入）",
                max_length=64,
                unique=True,
                verbose_name="SKU 编码",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                default="件", max_length=20, verbose_name="计量单位"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="barcode",
            field=models.CharField(
                help_text="批次识别码（数字）",
                max_length=64,
                unique=True,
                verbose_name="批次条码",
            ),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="batch_number",
            field=models.CharField(max_length=100, verbose_name="批次号"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="过期日期"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="warehouse.item",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="production_date",
            field=models.DateField(blank=True, null=True, verbose_name="生产日期"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="quantity_units",
            field=models.PositiveIntegerField(default=0, verbose_name="库存数量"),
        ),
        migrations.AlterField(
            model_name="itembatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="alt",
            field=models.CharField(blank=True, max_length=200, verbose_name="替代文本"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="item_images/", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="warehouse.item",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="capacity_volume",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="容积"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(max_length=64, unique=True, verbose_name="编码"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=120, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="location",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="movement",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="warehouse.itembatch",
                verbose_name="批次",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="movement",
            name="direction",
            field=models.CharField(
                choices=[("IN", "入库"), ("OUT", "出库")],
                max_length=3,
                verbose_name="方向",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.location",
                verbose_name="货位",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="movement",
            name="quantity_units",
            field=models.PositiveIntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="movement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
    ]
